var danePakiety =[
  {
    "pakiety": "car",
    "Freq": 4,
    "pobrania": 167669,
    "url": "https://www.rdocumentation.org/packages/car",
    "doswiadczenie_R_mean": 3.5,
    "doswiadczenie_analiza_mean": 6.6,
    "doswiadczenie_R_med": 2.25,
    "doswiadczenie_analiza_med": 3.75,
    "dosw": true
  },
  {
    "pakiety": "caret",
    "Freq": 6,
    "pobrania": 118006,
    "url": "https://www.rdocumentation.org/packages/caret",
    "doswiadczenie_R_mean": 2.6667,
    "doswiadczenie_analiza_mean": 3.6667,
    "doswiadczenie_R_med": 2.25,
    "doswiadczenie_analiza_med": 2.75,
    "dosw": true
  },
  {
    "pakiety": "cluster",
    "Freq": 3,
    "pobrania": 100664,
    "url": "https://www.rdocumentation.org/packages/cluster",
    "doswiadczenie_R_mean": 4,
    "doswiadczenie_analiza_mean": 3.5,
    "doswiadczenie_R_med": 4,
    "doswiadczenie_analiza_med": 3.5,
    "dosw": false
  },
  {
    "pakiety": "data.table",
    "Freq": 11,
    "pobrania": 211786,
    "url": "https://www.rdocumentation.org/packages/data.table",
    "doswiadczenie_R_mean": 2.9091,
    "doswiadczenie_analiza_mean": 5.7,
    "doswiadczenie_R_med": 3,
    "doswiadczenie_analiza_med": 4,
    "dosw": true
  },
  {
    "pakiety": "devtools",
    "Freq": 2,
    "pobrania": 141122,
    "url": "https://www.rdocumentation.org/packages/devtools",
    "doswiadczenie_R_mean": 1.5,
    "doswiadczenie_analiza_mean": 1.5,
    "doswiadczenie_R_med": 1.5,
    "doswiadczenie_analiza_med": 1.5,
    "dosw": false
  },
  {
    "pakiety": "dplyr",
    "Freq": 51,
    "pobrania": 262838,
    "url": "https://www.rdocumentation.org/packages/dplyr",
    "doswiadczenie_R_mean": 3.03,
    "doswiadczenie_analiza_mean": 4.1837,
    "doswiadczenie_R_med": 2,
    "doswiadczenie_analiza_med": 4,
    "dosw": true
  },
  {
    "pakiety": "DT",
    "Freq": 2,
    "pobrania": 34788,
    "url": "https://www.rdocumentation.org/packages/DT",
    "doswiadczenie_R_mean": 4.5,
    "doswiadczenie_analiza_mean": 3.5,
    "doswiadczenie_R_med": 4.5,
    "doswiadczenie_analiza_med": 3.5,
    "dosw": false
  },
  {
    "pakiety": "flexdashboard",
    "Freq": 2,
    "pobrania": 4745,
    "url": "https://www.rdocumentation.org/packages/flexdashboard",
    "doswiadczenie_R_mean": 2.5,
    "doswiadczenie_analiza_mean": 2.5,
    "doswiadczenie_R_med": 2.5,
    "doswiadczenie_analiza_med": 2.5,
    "dosw": false
  },
  {
    "pakiety": "FSelectorRcpp",
    "Freq": 2,
    "pobrania": 0,
    "url": "https://www.rdocumentation.org/packages/FSelectorRcpp",
    "doswiadczenie_R_mean": 4.5,
    "doswiadczenie_analiza_mean": 4,
    "doswiadczenie_R_med": 4.5,
    "doswiadczenie_analiza_med": 4,
    "dosw": false
  },
  {
    "pakiety": "gbm",
    "Freq": 2,
    "pobrania": 22500,
    "url": "https://www.rdocumentation.org/packages/gbm",
    "doswiadczenie_R_mean": 4.5,
    "doswiadczenie_analiza_mean": 8,
    "doswiadczenie_R_med": 4.5,
    "doswiadczenie_analiza_med": 8,
    "dosw": true
  },
  {
    "pakiety": "ggplot2",
    "Freq": 35,
    "pobrania": 446891,
    "url": "https://www.rdocumentation.org/packages/ggplot2",
    "doswiadczenie_R_mean": 3.1143,
    "doswiadczenie_analiza_mean": 4.5143,
    "doswiadczenie_R_med": 2,
    "doswiadczenie_analiza_med": 4,
    "dosw": true
  },
  {
    "pakiety": "glm",
    "Freq": 4,
    "pobrania": 0,
    "url": "https://www.rdocumentation.org/packages/glm",
    "doswiadczenie_R_mean": 2.875,
    "doswiadczenie_analiza_mean": 3.875,
    "doswiadczenie_R_med": 2.5,
    "doswiadczenie_analiza_med": 3.5,
    "dosw": true
  },
  {
    "pakiety": "glmnet",
    "Freq": 3,
    "pobrania": 41297,
    "url": "https://www.rdocumentation.org/packages/glmnet",
    "doswiadczenie_R_mean": 3.3333,
    "doswiadczenie_analiza_mean": 2.6667,
    "doswiadczenie_R_med": 4,
    "doswiadczenie_analiza_med": 3,
    "dosw": false
  },
  {
    "pakiety": "gmodels",
    "Freq": 2,
    "pobrania": 33056,
    "url": "https://www.rdocumentation.org/packages/gmodels",
    "doswiadczenie_R_mean": 1.5,
    "doswiadczenie_analiza_mean": 7,
    "doswiadczenie_R_med": 1.5,
    "doswiadczenie_analiza_med": 7,
    "dosw": true
  },
  {
    "pakiety": "googleAnalyticsR",
    "Freq": 2,
    "pobrania": 2043,
    "url": "https://www.rdocumentation.org/packages/googleAnalyticsR",
    "doswiadczenie_R_mean": 0.5,
    "doswiadczenie_analiza_mean": 3.5,
    "doswiadczenie_R_med": 0.5,
    "doswiadczenie_analiza_med": 3.5,
    "dosw": true
  },
  {
    "pakiety": "gtools",
    "Freq": 2,
    "pobrania": 91541,
    "url": "https://www.rdocumentation.org/packages/gtools",
    "doswiadczenie_R_mean": 1,
    "doswiadczenie_analiza_mean": 6,
    "doswiadczenie_R_med": 1,
    "doswiadczenie_analiza_med": 6,
    "dosw": true
  },
  {
    "pakiety": "h2o",
    "Freq": 4,
    "pobrania": 11373,
    "url": "https://www.rdocumentation.org/packages/h2o",
    "doswiadczenie_R_mean": 3.75,
    "doswiadczenie_analiza_mean": 4.25,
    "doswiadczenie_R_med": 4,
    "doswiadczenie_analiza_med": 4,
    "dosw": true
  },
  {
    "pakiety": "haven",
    "Freq": 3,
    "pobrania": 50915,
    "url": "https://www.rdocumentation.org/packages/haven",
    "doswiadczenie_R_mean": 7,
    "doswiadczenie_analiza_mean": 8.5,
    "doswiadczenie_R_med": 7,
    "doswiadczenie_analiza_med": 8.5,
    "dosw": true
  },
  {
    "pakiety": "jsonlite",
    "Freq": 3,
    "pobrania": 355398,
    "url": "https://www.rdocumentation.org/packages/jsonlite",
    "doswiadczenie_R_mean": 4,
    "doswiadczenie_analiza_mean": 4,
    "doswiadczenie_R_med": 4,
    "doswiadczenie_analiza_med": 4,
    "dosw": false
  },
  {
    "pakiety": "knitr",
    "Freq": 3,
    "pobrania": 215797,
    "url": "https://www.rdocumentation.org/packages/knitr",
    "doswiadczenie_R_mean": 7,
    "doswiadczenie_analiza_mean": 8,
    "doswiadczenie_R_med": 6,
    "doswiadczenie_analiza_med": 9,
    "dosw": true
  },
  {
    "pakiety": "leaflet",
    "Freq": 4,
    "pobrania": 19617,
    "url": "https://www.rdocumentation.org/packages/leaflet",
    "doswiadczenie_R_mean": 3,
    "doswiadczenie_analiza_mean": 3.5,
    "doswiadczenie_R_med": 2,
    "doswiadczenie_analiza_med": 3.5,
    "dosw": true
  },
  {
    "pakiety": "limma",
    "Freq": 2,
    "pobrania": 60,
    "url": "https://www.rdocumentation.org/packages/limma",
    "doswiadczenie_R_mean": 6,
    "doswiadczenie_analiza_mean": 7,
    "doswiadczenie_R_med": 6,
    "doswiadczenie_analiza_med": 7,
    "dosw": true
  },
  {
    "pakiety": "lme4",
    "Freq": 5,
    "pobrania": 164632,
    "url": "https://www.rdocumentation.org/packages/lme4",
    "doswiadczenie_R_mean": 4.9,
    "doswiadczenie_analiza_mean": 5.4,
    "doswiadczenie_R_med": 4,
    "doswiadczenie_analiza_med": 4,
    "dosw": true
  },
  {
    "pakiety": "lmtest",
    "Freq": 2,
    "pobrania": 105566,
    "url": "https://www.rdocumentation.org/packages/lmtest",
    "doswiadczenie_R_mean": 2,
    "doswiadczenie_analiza_mean": 3.5,
    "doswiadczenie_R_med": 2,
    "doswiadczenie_analiza_med": 3.5,
    "dosw": true
  },
  {
    "pakiety": "lubridate",
    "Freq": 3,
    "pobrania": 123933,
    "url": "https://www.rdocumentation.org/packages/lubridate",
    "doswiadczenie_R_mean": 6,
    "doswiadczenie_analiza_mean": 9,
    "doswiadczenie_R_med": 6,
    "doswiadczenie_analiza_med": 9,
    "dosw": true
  },
  {
    "pakiety": "magrittr",
    "Freq": 2,
    "pobrania": 300400,
    "url": "https://www.rdocumentation.org/packages/magrittr",
    "doswiadczenie_R_mean": 5.5,
    "doswiadczenie_analiza_mean": 4,
    "doswiadczenie_R_med": 5.5,
    "doswiadczenie_analiza_med": 4,
    "dosw": false
  },
  {
    "pakiety": "maptools",
    "Freq": 2,
    "pobrania": 54010,
    "url": "https://www.rdocumentation.org/packages/maptools",
    "doswiadczenie_R_mean": 6,
    "doswiadczenie_analiza_mean": 9.5,
    "doswiadczenie_R_med": 6,
    "doswiadczenie_analiza_med": 9.5,
    "dosw": true
  },
  {
    "pakiety": "multcomp",
    "Freq": 3,
    "pobrania": 58568,
    "url": "https://www.rdocumentation.org/packages/multcomp",
    "doswiadczenie_R_mean": 3.1667,
    "doswiadczenie_analiza_mean": 11.3333,
    "doswiadczenie_R_med": 2.5,
    "doswiadczenie_analiza_med": 10,
    "dosw": true
  },
  {
    "pakiety": "nlme",
    "Freq": 2,
    "pobrania": 64135,
    "url": "https://www.rdocumentation.org/packages/nlme",
    "doswiadczenie_R_mean": 3.25,
    "doswiadczenie_analiza_mean": 4,
    "doswiadczenie_R_med": 3.25,
    "doswiadczenie_analiza_med": 4,
    "dosw": true
  },
  {
    "pakiety": "plotly",
    "Freq": 10,
    "pobrania": 50649,
    "url": "https://www.rdocumentation.org/packages/plotly",
    "doswiadczenie_R_mean": 2.9,
    "doswiadczenie_analiza_mean": 3.4,
    "doswiadczenie_R_med": 2,
    "doswiadczenie_analiza_med": 3,
    "dosw": true
  },
  {
    "pakiety": "purrr",
    "Freq": 2,
    "pobrania": 76638,
    "url": "https://www.rdocumentation.org/packages/purrr",
    "doswiadczenie_R_mean": 8,
    "doswiadczenie_analiza_mean": 8,
    "doswiadczenie_R_med": 8,
    "doswiadczenie_analiza_med": 8,
    "dosw": false
  },
  {
    "pakiety": "randomForest",
    "Freq": 2,
    "pobrania": 61444,
    "url": "https://www.rdocumentation.org/packages/randomForest",
    "doswiadczenie_R_mean": 2.5,
    "doswiadczenie_analiza_mean": 2,
    "doswiadczenie_R_med": 2.5,
    "doswiadczenie_analiza_med": 2,
    "dosw": false
  },
  {
    "pakiety": "Rcpp",
    "Freq": 2,
    "pobrania": 557096,
    "url": "https://www.rdocumentation.org/packages/Rcpp",
    "doswiadczenie_R_mean": 6.3333,
    "doswiadczenie_analiza_mean": 8.3333,
    "doswiadczenie_R_med": 5,
    "doswiadczenie_analiza_med": 5,
    "dosw": true
  },
  {
    "pakiety": "readr",
    "Freq": 2,
    "pobrania": 204283,
    "url": "https://www.rdocumentation.org/packages/readr",
    "doswiadczenie_R_mean": 1,
    "doswiadczenie_analiza_mean": 1.5,
    "doswiadczenie_R_med": 1,
    "doswiadczenie_analiza_med": 1.5,
    "dosw": true
  },
  {
    "pakiety": "relaimpo",
    "Freq": 2,
    "pobrania": 2459,
    "url": "https://www.rdocumentation.org/packages/relaimpo",
    "doswiadczenie_R_mean": 3,
    "doswiadczenie_analiza_mean": 5,
    "doswiadczenie_R_med": 3,
    "doswiadczenie_analiza_med": 5,
    "dosw": true
  },
  {
    "pakiety": "reshape2",
    "Freq": 2,
    "pobrania": 293765,
    "url": "https://www.rdocumentation.org/packages/reshape2",
    "doswiadczenie_R_mean": 4.25,
    "doswiadczenie_analiza_mean": 4.25,
    "doswiadczenie_R_med": 4.25,
    "doswiadczenie_analiza_med": 4.25,
    "dosw": false
  },
  {
    "pakiety": "rmarkdown",
    "Freq": 6,
    "pobrania": 202612,
    "url": "https://www.rdocumentation.org/packages/rmarkdown",
    "doswiadczenie_R_mean": 4,
    "doswiadczenie_analiza_mean": 5,
    "doswiadczenie_R_med": 3,
    "doswiadczenie_analiza_med": 2.5,
    "dosw": true
  },
  {
    "pakiety": "RODBC",
    "Freq": 3,
    "pobrania": 37841,
    "url": "https://www.rdocumentation.org/packages/RODBC",
    "doswiadczenie_R_mean": 2.6667,
    "doswiadczenie_analiza_mean": 3,
    "doswiadczenie_R_med": 3,
    "doswiadczenie_analiza_med": 3,
    "dosw": true
  },
  {
    "pakiety": "rpart",
    "Freq": 2,
    "pobrania": 48259,
    "url": "https://www.rdocumentation.org/packages/rpart",
    "doswiadczenie_R_mean": 1,
    "doswiadczenie_analiza_mean": 2,
    "doswiadczenie_R_med": 1,
    "doswiadczenie_analiza_med": 2,
    "dosw": true
  },
  {
    "pakiety": "RPostgreSQL",
    "Freq": 2,
    "pobrania": 20675,
    "url": "https://www.rdocumentation.org/packages/RPostgreSQL",
    "doswiadczenie_R_mean": 3.5,
    "doswiadczenie_analiza_mean": 5,
    "doswiadczenie_R_med": 3.5,
    "doswiadczenie_analiza_med": 5,
    "dosw": true
  },
  {
    "pakiety": "RSQLite",
    "Freq": 2,
    "pobrania": 76107,
    "url": "https://www.rdocumentation.org/packages/RSQLite",
    "doswiadczenie_R_mean": 2.5,
    "doswiadczenie_analiza_mean": 2.5,
    "doswiadczenie_R_med": 2.5,
    "doswiadczenie_analiza_med": 2.5,
    "dosw": false
  },
  {
    "pakiety": "rvest",
    "Freq": 2,
    "pobrania": 50651,
    "url": "https://www.rdocumentation.org/packages/rvest",
    "doswiadczenie_R_mean": 4,
    "doswiadczenie_analiza_mean": 4.5,
    "doswiadczenie_R_med": 4,
    "doswiadczenie_analiza_med": 4.5,
    "dosw": true
  },
  {
    "pakiety": "sandwich",
    "Freq": 2,
    "pobrania": 80267,
    "url": "https://www.rdocumentation.org/packages/sandwich",
    "doswiadczenie_R_mean": 6,
    "doswiadczenie_analiza_mean": 7,
    "doswiadczenie_R_med": 6,
    "doswiadczenie_analiza_med": 7,
    "dosw": true
  },
  {
    "pakiety": "shiny",
    "Freq": 16,
    "pobrania": 180363,
    "url": "https://www.rdocumentation.org/packages/shiny",
    "doswiadczenie_R_mean": 3.6875,
    "doswiadczenie_analiza_mean": 4.5,
    "doswiadczenie_R_med": 4.5,
    "doswiadczenie_analiza_med": 4,
    "dosw": true
  },
  {
    "pakiety": "spdep",
    "Freq": 2,
    "pobrania": 29542,
    "url": "https://www.rdocumentation.org/packages/spdep",
    "doswiadczenie_R_mean": 6.5,
    "doswiadczenie_analiza_mean": 11,
    "doswiadczenie_R_med": 6.5,
    "doswiadczenie_analiza_med": 11,
    "dosw": true
  },
  {
    "pakiety": "sqldf",
    "Freq": 2,
    "pobrania": 97239,
    "url": "https://www.rdocumentation.org/packages/sqldf",
    "doswiadczenie_R_mean": 1,
    "doswiadczenie_analiza_mean": 3,
    "doswiadczenie_R_med": 1,
    "doswiadczenie_analiza_med": 3,
    "dosw": true
  },
  {
    "pakiety": "stringi",
    "Freq": 11,
    "pobrania": 410216,
    "url": "https://www.rdocumentation.org/packages/stringi",
    "doswiadczenie_R_mean": 3.0909,
    "doswiadczenie_analiza_mean": 3.35,
    "doswiadczenie_R_med": 2,
    "doswiadczenie_analiza_med": 3,
    "dosw": true
  },
  {
    "pakiety": "stringr",
    "Freq": 6,
    "pobrania": 363610,
    "url": "https://www.rdocumentation.org/packages/stringr",
    "doswiadczenie_R_mean": 1.8,
    "doswiadczenie_analiza_mean": 6.4,
    "doswiadczenie_R_med": 1,
    "doswiadczenie_analiza_med": 4,
    "dosw": true
  },
  {
    "pakiety": "survey",
    "Freq": 4,
    "pobrania": 14959,
    "url": "https://www.rdocumentation.org/packages/survey",
    "doswiadczenie_R_mean": 5.6667,
    "doswiadczenie_analiza_mean": 6.6667,
    "doswiadczenie_R_med": 4,
    "doswiadczenie_analiza_med": 6,
    "dosw": true
  },
  {
    "pakiety": "survival",
    "Freq": 3,
    "pobrania": 165814,
    "url": "https://www.rdocumentation.org/packages/survival",
    "doswiadczenie_R_mean": 3,
    "doswiadczenie_analiza_mean": 2.5,
    "doswiadczenie_R_med": 3,
    "doswiadczenie_analiza_med": 3,
    "dosw": false
  },
  {
    "pakiety": "tidyr",
    "Freq": 15,
    "pobrania": 138805,
    "url": "https://www.rdocumentation.org/packages/tidyr",
    "doswiadczenie_R_mean": 4.1333,
    "doswiadczenie_analiza_mean": 4.3333,
    "doswiadczenie_R_med": 4,
    "doswiadczenie_analiza_med": 4,
    "dosw": true
  },
  {
    "pakiety": "tidyverse",
    "Freq": 10,
    "pobrania": 49217,
    "url": "https://www.rdocumentation.org/packages/tidyverse",
    "doswiadczenie_R_mean": 2.85,
    "doswiadczenie_analiza_mean": 4.35,
    "doswiadczenie_R_med": 2.75,
    "doswiadczenie_analiza_med": 4,
    "dosw": true
  },
  {
    "pakiety": "tm",
    "Freq": 2,
    "pobrania": 65734,
    "url": "https://www.rdocumentation.org/packages/tm",
    "doswiadczenie_R_mean": 1.3333,
    "doswiadczenie_analiza_mean": 1.6667,
    "doswiadczenie_R_med": 1,
    "doswiadczenie_analiza_med": 2,
    "dosw": true
  },
  {
    "pakiety": "xgboost",
    "Freq": 4,
    "pobrania": 14813,
    "url": "https://www.rdocumentation.org/packages/xgboost",
    "doswiadczenie_R_mean": 3,
    "doswiadczenie_analiza_mean": 2.75,
    "doswiadczenie_R_med": 2.5,
    "doswiadczenie_analiza_med": 2,
    "dosw": false
  },
  {
    "pakiety": "xlsx",
    "Freq": 2,
    "pobrania": 67219,
    "url": "https://www.rdocumentation.org/packages/xlsx",
    "doswiadczenie_R_mean": 3,
    "doswiadczenie_analiza_mean": 2.8333,
    "doswiadczenie_R_med": 2,
    "doswiadczenie_analiza_med": 3,
    "dosw": false
  },
  {
    "pakiety": "xts",
    "Freq": 3,
    "pobrania": 57053,
    "url": "https://www.rdocumentation.org/packages/xts",
    "doswiadczenie_R_mean": 4.6667,
    "doswiadczenie_analiza_mean": 9.6667,
    "doswiadczenie_R_med": 3,
    "doswiadczenie_analiza_med": 10,
    "dosw": true
  }
] ;