var dane = [
  {
    "warsztat": "Kombajn do uczenia maszynowego - MLR w praktyce",
    "wiek": 31.7895,
    "ile": 22,
    "ile_rezerwa": 2,
    "kobiety": 2,
    "mezczyzni": 19,
    "plec_inne": 1,
    "st_nauk": 50,
    "analizy_0_2": 31.8182,
    "analizy_2_6": 31.8182,
    "analizy_6_wiecej": 18.1818,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 22.7273,
    "analizy_R_6_wiecej": 9.0909,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "wizualizacja danych",
    "zaint3": "Big Data i hurtownie danych",
    "zaint1_ile": 77.2727,
    "zaint2_ile": 63.6364,
    "zaint3_ile": 50,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/313_Uczenie_Maszynowe_Narzedzia/sesja_popoludniowa",
    "pozycja": 1
  },
  {
    "warsztat": "Text mining w R",
    "wiek": 29.3333,
    "ile": 21,
    "ile_rezerwa": 1,
    "kobiety": 10,
    "mezczyzni": 7,
    "plec_inne": 4,
    "st_nauk": 47.619,
    "analizy_0_2": 28.5714,
    "analizy_2_6": 19.0476,
    "analizy_6_wiecej": 19.0476,
    "analizy_R_0_2": 47.619,
    "analizy_R_2_6": 19.0476,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "analiza tekstu",
    "zaint3": "R w biznesie",
    "zaint1_ile": 57.1429,
    "zaint2_ile": 33.3333,
    "zaint3_ile": 33.3333,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/317_Grafy_Analiza_Tekstu/sesja_popoludniowa",
    "pozycja": 2
  },
  {
    "warsztat": "mirt: skalowanie odpowiedzi lepsze niż PCA",
    "wiek": 30,
    "ile": 15,
    "ile_rezerwa": 0,
    "kobiety": 5,
    "mezczyzni": 9,
    "plec_inne": 1,
    "st_nauk": 40,
    "analizy_0_2": 26.6667,
    "analizy_2_6": 33.3333,
    "analizy_6_wiecej": 20,
    "analizy_R_0_2": 20,
    "analizy_R_2_6": 46.6667,
    "analizy_R_6_wiecej": 6.6667,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "R w biznesie",
    "zaint2": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint3": "wizualizacja danych",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 66.6667,
    "zaint3_ile": 60,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/316_Analiza_Wielowymiarowa/sesja_popoludniowa",
    "pozycja": 3
  },
  {
    "warsztat": "Klasyfikacja wieloetykietowa z pakietem R",
    "wiek": 30,
    "ile": 9,
    "ile_rezerwa": 0,
    "kobiety": 1,
    "mezczyzni": 7,
    "plec_inne": 1,
    "st_nauk": 44.4444,
    "analizy_0_2": 11.1111,
    "analizy_2_6": 55.5556,
    "analizy_6_wiecej": 22.2222,
    "analizy_R_0_2": 44.4444,
    "analizy_R_2_6": 33.3333,
    "analizy_R_6_wiecej": 11.1111,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "klastrowanie i segmentacja",
    "zaint2": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint3": "wizualizacja danych",
    "zaint1_ile": 33.3333,
    "zaint2_ile": 33.3333,
    "zaint3_ile": 33.3333,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/314_Uczenie_Maszynowe_Metody/sesja_popoludniowa",
    "pozycja": 4
  },
  {
    "warsztat": "Złożone schematy doboru próby - pakiet survey",
    "wiek": 28.8571,
    "ile": 9,
    "ile_rezerwa": 0,
    "kobiety": 3,
    "mezczyzni": 6,
    "plec_inne": 0,
    "st_nauk": 44.4444,
    "analizy_0_2": 33.3333,
    "analizy_2_6": 33.3333,
    "analizy_6_wiecej": 22.2222,
    "analizy_R_0_2": 66.6667,
    "analizy_R_2_6": 22.2222,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "metodologia statystyczna",
    "zaint3": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 55.5556,
    "zaint3_ile": 55.5556,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/310_Sondaze/sesja_popoludniowa",
    "pozycja": 5
  },
  {
    "warsztat": "Efektywna i efektowna wizualizacja w ggplot2",
    "wiek": 33,
    "ile": 6,
    "ile_rezerwa": 0,
    "kobiety": 2,
    "mezczyzni": 2,
    "plec_inne": 2,
    "st_nauk": 50,
    "analizy_0_2": 0,
    "analizy_2_6": 16.6667,
    "analizy_6_wiecej": 33.3333,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 0,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "Big Data i hurtownie danych",
    "zaint2": "metodologia statystyczna",
    "zaint3": "odtwarzalne obliczenia",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 50,
    "zaint3_ile": 50,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/315_Wizualizacje/sesja_popoludniowa",
    "pozycja": 6
  },
  {
    "warsztat": "Web scraping w R i nie tylko",
    "wiek": 26.25,
    "ile": 5,
    "ile_rezerwa": 0,
    "kobiety": 0,
    "mezczyzni": 4,
    "plec_inne": 1,
    "st_nauk": 60,
    "analizy_0_2": 20,
    "analizy_2_6": 40,
    "analizy_6_wiecej": 20,
    "analizy_R_0_2": 0,
    "analizy_R_2_6": 60,
    "analizy_R_6_wiecej": 20,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "analiza tekstu",
    "zaint3": "Big Data i hurtownie danych",
    "zaint1_ile": 80,
    "zaint2_ile": 60,
    "zaint3_ile": 60,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/311_Web_Harvesting/sesja_popoludniowa",
    "pozycja": 7
  },
  {
    "warsztat": "Zastosowanie R w Power BI",
    "wiek": 27.75,
    "ile": 5,
    "ile_rezerwa": 0,
    "kobiety": 1,
    "mezczyzni": 3,
    "plec_inne": 1,
    "st_nauk": 60,
    "analizy_0_2": 40,
    "analizy_2_6": 0,
    "analizy_6_wiecej": 20,
    "analizy_R_0_2": 60,
    "analizy_R_2_6": 0,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "tworzenie raportów i dashboardów",
    "zaint2": "wizualizacja danych",
    "zaint3": "analiza tekstu",
    "zaint1_ile": 80,
    "zaint2_ile": 80,
    "zaint3_ile": 60,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/312_Uczenie_Maszynowe_Microsoft_Self_BI_Services/sesja_popoludniowa",
    "pozycja": 8
  },
  {
    "warsztat": "Nie pisz kodu, pisz prozę - wprowadzenie do pakietu dplyr",
    "wiek": 34,
    "ile": 3,
    "ile_rezerwa": 0,
    "kobiety": 1,
    "mezczyzni": 2,
    "plec_inne": 0,
    "st_nauk": 0,
    "analizy_0_2": 0,
    "analizy_2_6": 33.3333,
    "analizy_6_wiecej": 66.6667,
    "analizy_R_0_2": 100,
    "analizy_R_2_6": 0,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "ekonomia/finanse i ubezpieczenia",
    "zaint2": "wizualizacja danych",
    "zaint3": "badania kliniczne",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 66.6667,
    "zaint3_ile": 33.3333,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/318_Wydajnosc/sesja_popoludniowa",
    "pozycja": 9
  },
  {
    "warsztat": "Analiza danych sondażowych w R",
    "wiek": 31.4545,
    "ile": 22,
    "ile_rezerwa": 2,
    "kobiety": 6,
    "mezczyzni": 10,
    "plec_inne": 6,
    "st_nauk": 50,
    "analizy_0_2": 13.6364,
    "analizy_2_6": 31.8182,
    "analizy_6_wiecej": 18.1818,
    "analizy_R_0_2": 45.4545,
    "analizy_R_2_6": 18.1818,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja poranna",
    "sciezka": "mirt: skalowanie odpowiedzi lepsze niż PCA",
    "zaint1": "wizualizacja danych",
    "zaint2": "R w badaniach społecznych",
    "zaint3": "analiza tekstu",
    "zaint1_ile": 59.0909,
    "zaint2_ile": 45.4545,
    "zaint3_ile": 40.9091,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/310_Sondaze/sesja_poranna",
    "pozycja": 1
  },
  {
    "warsztat": "Machine Learning w R przy użyciu H2O",
    "wiek": 30.7222,
    "ile": 22,
    "ile_rezerwa": 2,
    "kobiety": 6,
    "mezczyzni": 15,
    "plec_inne": 1,
    "st_nauk": 40.9091,
    "analizy_0_2": 45.4545,
    "analizy_2_6": 22.7273,
    "analizy_6_wiecej": 13.6364,
    "analizy_R_0_2": 54.5455,
    "analizy_R_2_6": 18.1818,
    "analizy_R_6_wiecej": 4.5455,
    "sesja": "sesja poranna",
    "sciezka": "Kombajn do uczenia maszynowego - MLR w praktyce",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "wizualizacja danych",
    "zaint3": "Big Data i hurtownie danych",
    "zaint1_ile": 72.7273,
    "zaint2_ile": 54.5455,
    "zaint3_ile": 36.3636,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/313_Uczenie_Maszynowe_Narzedzia/sesja_poranna",
    "pozycja": 2
  },
  {
    "warsztat": "Kiedy brakuje wydajności... R i C++ = Rcpp",
    "wiek": 26.9231,
    "ile": 15,
    "ile_rezerwa": 0,
    "kobiety": 5,
    "mezczyzni": 9,
    "plec_inne": 1,
    "st_nauk": 40,
    "analizy_0_2": 26.6667,
    "analizy_2_6": 40,
    "analizy_6_wiecej": 13.3333,
    "analizy_R_0_2": 40,
    "analizy_R_2_6": 33.3333,
    "analizy_R_6_wiecej": 13.3333,
    "sesja": "sesja poranna",
    "sciezka": "Text mining w R",
    "zaint1": "wizualizacja danych",
    "zaint2": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint3": "tworzenie raportów i dashboardów",
    "zaint1_ile": 73.3333,
    "zaint2_ile": 53.3333,
    "zaint3_ile": 46.6667,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/318_Wydajnosc/sesja_poranna",
    "pozycja": 3
  },
  {
    "warsztat": "Interaktywne wizualizacje w R i plotly - case study",
    "wiek": 32.1111,
    "ile": 14,
    "ile_rezerwa": 0,
    "kobiety": 3,
    "mezczyzni": 8,
    "plec_inne": 3,
    "st_nauk": 64.2857,
    "analizy_0_2": 0,
    "analizy_2_6": 28.5714,
    "analizy_6_wiecej": 42.8571,
    "analizy_R_0_2": 57.1429,
    "analizy_R_2_6": 14.2857,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja poranna",
    "sciezka": "Efektywna i efektowna wizualizacja w ggplot2",
    "zaint1": "wizualizacja danych",
    "zaint2": "klastrowanie i segmentacja",
    "zaint3": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint1_ile": 64.2857,
    "zaint2_ile": 42.8571,
    "zaint3_ile": 42.8571,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/315_Wizualizacje/sesja_poranna",
    "pozycja": 4
  },
  {
    "warsztat": "XGBoost rządzi",
    "wiek": 31.8182,
    "ile": 12,
    "ile_rezerwa": 0,
    "kobiety": 1,
    "mezczyzni": 11,
    "plec_inne": 0,
    "st_nauk": 75,
    "analizy_0_2": 25,
    "analizy_2_6": 25,
    "analizy_6_wiecej": 33.3333,
    "analizy_R_0_2": 25,
    "analizy_R_2_6": 33.3333,
    "analizy_R_6_wiecej": 25,
    "sesja": "sesja poranna",
    "sciezka": "Kombajn do uczenia maszynowego - MLR w praktyce",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "metodologia statystyczna",
    "zaint3": "wizualizacja danych",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 58.3333,
    "zaint3_ile": 58.3333,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/314_Uczenie_Maszynowe_Metody/sesja_poranna",
    "pozycja": 5
  },
  {
    "warsztat": "Pakiet rvest, czyli web scrapingu wybrane przypadki",
    "wiek": 28.75,
    "ile": 7,
    "ile_rezerwa": 0,
    "kobiety": 3,
    "mezczyzni": 2,
    "plec_inne": 2,
    "st_nauk": 28.5714,
    "analizy_0_2": 28.5714,
    "analizy_2_6": 0,
    "analizy_6_wiecej": 28.5714,
    "analizy_R_0_2": 42.8571,
    "analizy_R_2_6": 14.2857,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja poranna",
    "sciezka": "Text mining w R",
    "zaint1": "metodologia statystyczna",
    "zaint2": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint3": "wizualizacja danych",
    "zaint1_ile": 42.8571,
    "zaint2_ile": 42.8571,
    "zaint3_ile": 42.8571,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/311_Web_Harvesting/sesja_poranna",
    "pozycja": 6
  },
  {
    "warsztat": "MicrosoftML - State of the art Machine Learning Microsoft",
    "wiek": 28,
    "ile": 6,
    "ile_rezerwa": 0,
    "kobiety": 2,
    "mezczyzni": 4,
    "plec_inne": 0,
    "st_nauk": 33.3333,
    "analizy_0_2": 50,
    "analizy_2_6": 33.3333,
    "analizy_6_wiecej": 16.6667,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 50,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja poranna",
    "sciezka": "Kombajn do uczenia maszynowego - MLR w praktyce",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "tworzenie raportów i dashboardów",
    "zaint3": "Big Data i hurtownie danych",
    "zaint1_ile": 83.3333,
    "zaint2_ile": 83.3333,
    "zaint3_ile": 66.6667,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/312_Uczenie_Maszynowe_Microsoft_Self_BI_Services/sesja_poranna",
    "pozycja": 7
  },
  {
    "warsztat": "Social Network Analysis w R",
    "wiek": 32.6667,
    "ile": 4,
    "ile_rezerwa": 0,
    "kobiety": 0,
    "mezczyzni": 3,
    "plec_inne": 1,
    "st_nauk": 75,
    "analizy_0_2": 50,
    "analizy_2_6": 0,
    "analizy_6_wiecej": 25,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 25,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja poranna",
    "sciezka": "Text mining w R",
    "zaint1": "analiza tekstu",
    "zaint2": "tworzenie raportów i dashboardów",
    "zaint3": "wizualizacja danych",
    "zaint1_ile": 50,
    "zaint2_ile": 50,
    "zaint3_ile": 50,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/317_Grafy_Analiza_Tekstu/sesja_poranna",
    "pozycja": 8
  },
  {
    "warsztat": "Wróżenie z punktów - ordynacja w eksploracji danych",
    "wiek": 30.6667,
    "ile": 3,
    "ile_rezerwa": 0,
    "kobiety": 0,
    "mezczyzni": 3,
    "plec_inne": 0,
    "st_nauk": 100,
    "analizy_0_2": 0,
    "analizy_2_6": 33.3333,
    "analizy_6_wiecej": 33.3333,
    "analizy_R_0_2": 0,
    "analizy_R_2_6": 33.3333,
    "analizy_R_6_wiecej": 33.3333,
    "sesja": "sesja poranna",
    "sciezka": "brak",
    "zaint1": "analiza tekstu",
    "zaint2": "metodologia statystyczna",
    "zaint3": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint1_ile": 100,
    "zaint2_ile": 100,
    "zaint3_ile": 100,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/316_Analiza_Wielowymiarowa/sesja_poranna",
    "pozycja": 9
  }
] 