var dane = [
  {
    "warsztat": "Kombajn do uczenia maszynowego - MLR w praktyce",
    "wiek": 32.4717,
    "ile": 26,
    "ile_rezerwa": 6,
    "kobiety": 2,
    "mezczyzni": 22,
    "plec_inne": 2,
    "st_nauk": 53.8462,
    "analizy_0_2": 26.9231,
    "analizy_2_6": 26.9231,
    "analizy_6_wiecej": 26.9231,
    "analizy_R_0_2": 46.1538,
    "analizy_R_2_6": 26.9231,
    "analizy_R_6_wiecej": 7.6923,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "wizualizacja danych",
    "zaint3": "Big Data i hurtownie danych",
    "zaint1_ile": 69.2308,
    "zaint2_ile": 57.6923,
    "zaint3_ile": 50,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/313_Uczenie_Maszynowe_Narzedzia/sesja_popoludniowa",
    "pozycja": 1
  },
  {
    "warsztat": "Text mining w R",
    "wiek": 29.4597,
    "ile": 24,
    "ile_rezerwa": 4,
    "kobiety": 10,
    "mezczyzni": 9,
    "plec_inne": 5,
    "st_nauk": 45.8333,
    "analizy_0_2": 29.1667,
    "analizy_2_6": 16.6667,
    "analizy_6_wiecej": 20.8333,
    "analizy_R_0_2": 45.8333,
    "analizy_R_2_6": 20.8333,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "analiza tekstu",
    "zaint3": "R w biznesie",
    "zaint1_ile": 54.1667,
    "zaint2_ile": 37.5,
    "zaint3_ile": 37.5,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/317_Grafy_Analiza_Tekstu/sesja_popoludniowa",
    "pozycja": 2
  },
  {
    "warsztat": "mirt: skalowanie odpowiedzi lepsze niż PCA",
    "wiek": 29.6405,
    "ile": 15,
    "ile_rezerwa": 0,
    "kobiety": 5,
    "mezczyzni": 9,
    "plec_inne": 1,
    "st_nauk": 33.3333,
    "analizy_0_2": 33.3333,
    "analizy_2_6": 33.3333,
    "analizy_6_wiecej": 13.3333,
    "analizy_R_0_2": 26.6667,
    "analizy_R_2_6": 40,
    "analizy_R_6_wiecej": 6.6667,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "R w biznesie",
    "zaint3": "wizualizacja danych",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 60,
    "zaint3_ile": 60,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/316_Analiza_Wielowymiarowa/sesja_popoludniowa",
    "pozycja": 3
  },
  {
    "warsztat": "Klasyfikacja wieloetykietowa z pakietem R",
    "wiek": 31.8301,
    "ile": 12,
    "ile_rezerwa": 0,
    "kobiety": 3,
    "mezczyzni": 8,
    "plec_inne": 1,
    "st_nauk": 50,
    "analizy_0_2": 8.3333,
    "analizy_2_6": 50,
    "analizy_6_wiecej": 33.3333,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 25,
    "analizy_R_6_wiecej": 16.6667,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "klastrowanie i segmentacja",
    "zaint2": "R w biznesie",
    "zaint3": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint1_ile": 41.6667,
    "zaint2_ile": 33.3333,
    "zaint3_ile": 33.3333,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/314_Uczenie_Maszynowe_Metody/sesja_popoludniowa",
    "pozycja": 4
  },
  {
    "warsztat": "Zastosowanie R w Power BI",
    "wiek": 30.1116,
    "ile": 11,
    "ile_rezerwa": 0,
    "kobiety": 4,
    "mezczyzni": 6,
    "plec_inne": 1,
    "st_nauk": 54.5455,
    "analizy_0_2": 36.3636,
    "analizy_2_6": 9.0909,
    "analizy_6_wiecej": 27.2727,
    "analizy_R_0_2": 63.6364,
    "analizy_R_2_6": 9.0909,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "Big Data i hurtownie danych",
    "zaint2": "R w biznesie",
    "zaint3": "tworzenie raportów i dashboardów",
    "zaint1_ile": 63.6364,
    "zaint2_ile": 63.6364,
    "zaint3_ile": 63.6364,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/312_Uczenie_Maszynowe_Microsoft_Self_BI_Services/sesja_popoludniowa",
    "pozycja": 5
  },
  {
    "warsztat": "Złożone schematy doboru próby - pakiet survey",
    "wiek": 27.6968,
    "ile": 11,
    "ile_rezerwa": 0,
    "kobiety": 5,
    "mezczyzni": 6,
    "plec_inne": 0,
    "st_nauk": 36.3636,
    "analizy_0_2": 36.3636,
    "analizy_2_6": 27.2727,
    "analizy_6_wiecej": 18.1818,
    "analizy_R_0_2": 54.5455,
    "analizy_R_2_6": 27.2727,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "metodologia statystyczna",
    "zaint3": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint1_ile": 63.6364,
    "zaint2_ile": 54.5455,
    "zaint3_ile": 54.5455,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/310_Sondaze/sesja_popoludniowa",
    "pozycja": 6
  },
  {
    "warsztat": "Web scraping w R i nie tylko",
    "wiek": 30.0646,
    "ile": 10,
    "ile_rezerwa": 0,
    "kobiety": 2,
    "mezczyzni": 6,
    "plec_inne": 2,
    "st_nauk": 70,
    "analizy_0_2": 10,
    "analizy_2_6": 40,
    "analizy_6_wiecej": 20,
    "analizy_R_0_2": 0,
    "analizy_R_2_6": 60,
    "analizy_R_6_wiecej": 10,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "integracja R z innymi językami/środowiskami",
    "zaint3": "R w biznesie",
    "zaint1_ile": 70,
    "zaint2_ile": 40,
    "zaint3_ile": 40,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/311_Web_Harvesting/sesja_popoludniowa",
    "pozycja": 7
  },
  {
    "warsztat": "Efektywna i efektowna wizualizacja w ggplot2",
    "wiek": 34.6674,
    "ile": 9,
    "ile_rezerwa": 0,
    "kobiety": 3,
    "mezczyzni": 4,
    "plec_inne": 2,
    "st_nauk": 66.6667,
    "analizy_0_2": 0,
    "analizy_2_6": 22.2222,
    "analizy_6_wiecej": 44.4444,
    "analizy_R_0_2": 44.4444,
    "analizy_R_2_6": 0,
    "analizy_R_6_wiecej": 22.2222,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "Big Data i hurtownie danych",
    "zaint3": "metodologia statystyczna",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 55.5556,
    "zaint3_ile": 55.5556,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/315_Wizualizacje/sesja_popoludniowa",
    "pozycja": 8
  },
  {
    "warsztat": "Nie pisz kodu, pisz prozę - wprowadzenie do pakietu dplyr",
    "wiek": 36.1036,
    "ile": 5,
    "ile_rezerwa": 0,
    "kobiety": 3,
    "mezczyzni": 2,
    "plec_inne": 0,
    "st_nauk": 40,
    "analizy_0_2": 20,
    "analizy_2_6": 20,
    "analizy_6_wiecej": 60,
    "analizy_R_0_2": 100,
    "analizy_R_2_6": 0,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "ekonomia/finanse i ubezpieczenia",
    "zaint3": "metodologia statystyczna",
    "zaint1_ile": 60,
    "zaint2_ile": 40,
    "zaint3_ile": 40,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/318_Wydajnosc/sesja_popoludniowa",
    "pozycja": 9
  },
  {
    "warsztat": "Analiza danych sondażowych w R",
    "wiek": 31.9332,
    "ile": 24,
    "ile_rezerwa": 4,
    "kobiety": 7,
    "mezczyzni": 11,
    "plec_inne": 6,
    "st_nauk": 54.1667,
    "analizy_0_2": 12.5,
    "analizy_2_6": 33.3333,
    "analizy_6_wiecej": 20.8333,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 16.6667,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja poranna",
    "sciezka": "mirt: skalowanie odpowiedzi lepsze niż PCA",
    "zaint1": "wizualizacja danych",
    "zaint2": "R w badaniach społecznych",
    "zaint3": "analiza tekstu",
    "zaint1_ile": 58.3333,
    "zaint2_ile": 50,
    "zaint3_ile": 41.6667,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/310_Sondaze/sesja_poranna",
    "pozycja": 1
  },
  {
    "warsztat": "Machine Learning w R przy użyciu H2O",
    "wiek": 31.2136,
    "ile": 24,
    "ile_rezerwa": 4,
    "kobiety": 6,
    "mezczyzni": 17,
    "plec_inne": 1,
    "st_nauk": 37.5,
    "analizy_0_2": 41.6667,
    "analizy_2_6": 25,
    "analizy_6_wiecej": 16.6667,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 25,
    "analizy_R_6_wiecej": 4.1667,
    "sesja": "sesja poranna",
    "sciezka": "Kombajn do uczenia maszynowego - MLR w praktyce",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "wizualizacja danych",
    "zaint3": "Big Data i hurtownie danych",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 50,
    "zaint3_ile": 37.5,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/313_Uczenie_Maszynowe_Narzedzia/sesja_poranna",
    "pozycja": 2
  },
  {
    "warsztat": "Interaktywne wizualizacje w R i plotly - case study",
    "wiek": 33.5765,
    "ile": 21,
    "ile_rezerwa": 1,
    "kobiety": 5,
    "mezczyzni": 12,
    "plec_inne": 4,
    "st_nauk": 71.4286,
    "analizy_0_2": 0,
    "analizy_2_6": 28.5714,
    "analizy_6_wiecej": 47.619,
    "analizy_R_0_2": 47.619,
    "analizy_R_2_6": 19.0476,
    "analizy_R_6_wiecej": 9.5238,
    "sesja": "sesja poranna",
    "sciezka": "Efektywna i efektowna wizualizacja w ggplot2",
    "zaint1": "wizualizacja danych",
    "zaint2": "metodologia statystyczna",
    "zaint3": "klastrowanie i segmentacja",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 42.8571,
    "zaint3_ile": 38.0952,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/315_Wizualizacje/sesja_poranna",
    "pozycja": 3
  },
  {
    "warsztat": "Kiedy brakuje wydajności... R i C++ = Rcpp",
    "wiek": 26.6417,
    "ile": 16,
    "ile_rezerwa": 0,
    "kobiety": 6,
    "mezczyzni": 9,
    "plec_inne": 1,
    "st_nauk": 37.5,
    "analizy_0_2": 31.25,
    "analizy_2_6": 37.5,
    "analizy_6_wiecej": 12.5,
    "analizy_R_0_2": 37.5,
    "analizy_R_2_6": 37.5,
    "analizy_R_6_wiecej": 12.5,
    "sesja": "sesja poranna",
    "sciezka": "Text mining w R",
    "zaint1": "wizualizacja danych",
    "zaint2": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint3": "tworzenie raportów i dashboardów",
    "zaint1_ile": 75,
    "zaint2_ile": 56.25,
    "zaint3_ile": 43.75,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/318_Wydajnosc/sesja_poranna",
    "pozycja": 4
  },
  {
    "warsztat": "XGBoost rządzi",
    "wiek": 31.0829,
    "ile": 13,
    "ile_rezerwa": 0,
    "kobiety": 2,
    "mezczyzni": 11,
    "plec_inne": 0,
    "st_nauk": 69.2308,
    "analizy_0_2": 23.0769,
    "analizy_2_6": 23.0769,
    "analizy_6_wiecej": 30.7692,
    "analizy_R_0_2": 23.0769,
    "analizy_R_2_6": 30.7692,
    "analizy_R_6_wiecej": 23.0769,
    "sesja": "sesja poranna",
    "sciezka": "Kombajn do uczenia maszynowego - MLR w praktyce",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "metodologia statystyczna",
    "zaint3": "wizualizacja danych",
    "zaint1_ile": 61.5385,
    "zaint2_ile": 53.8462,
    "zaint3_ile": 53.8462,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/314_Uczenie_Maszynowe_Metody/sesja_poranna",
    "pozycja": 5
  },
  {
    "warsztat": "Social Network Analysis w R",
    "wiek": 32.768,
    "ile": 12,
    "ile_rezerwa": 0,
    "kobiety": 4,
    "mezczyzni": 6,
    "plec_inne": 2,
    "st_nauk": 58.3333,
    "analizy_0_2": 33.3333,
    "analizy_2_6": 16.6667,
    "analizy_6_wiecej": 33.3333,
    "analizy_R_0_2": 41.6667,
    "analizy_R_2_6": 33.3333,
    "analizy_R_6_wiecej": 8.3333,
    "sesja": "sesja poranna",
    "sciezka": "Text mining w R",
    "zaint1": "R w biznesie",
    "zaint2": "wizualizacja danych",
    "zaint3": "analiza tekstu",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 50,
    "zaint3_ile": 41.6667,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/317_Grafy_Analiza_Tekstu/sesja_poranna",
    "pozycja": 6
  },
  {
    "warsztat": "MicrosoftML - State of the art Machine Learning Microsoft",
    "wiek": 29.0679,
    "ile": 10,
    "ile_rezerwa": 0,
    "kobiety": 5,
    "mezczyzni": 5,
    "plec_inne": 0,
    "st_nauk": 50,
    "analizy_0_2": 40,
    "analizy_2_6": 40,
    "analizy_6_wiecej": 20,
    "analizy_R_0_2": 70,
    "analizy_R_2_6": 30,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja poranna",
    "sciezka": "Zastosowanie R w Power BI",
    "zaint1": "Big Data i hurtownie danych",
    "zaint2": "R w biznesie",
    "zaint3": "integracja R z innymi językami/środowiskami",
    "zaint1_ile": 80,
    "zaint2_ile": 80,
    "zaint3_ile": 70,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/312_Uczenie_Maszynowe_Microsoft_Self_BI_Services/sesja_poranna",
    "pozycja": 7
  },
  {
    "warsztat": "Pakiet rvest, czyli web scrapingu wybrane przypadki",
    "wiek": 30.8307,
    "ile": 10,
    "ile_rezerwa": 0,
    "kobiety": 3,
    "mezczyzni": 5,
    "plec_inne": 2,
    "st_nauk": 20,
    "analizy_0_2": 30,
    "analizy_2_6": 0,
    "analizy_6_wiecej": 30,
    "analizy_R_0_2": 40,
    "analizy_R_2_6": 20,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja poranna",
    "sciezka": "Text mining w R",
    "zaint1": "metodologia statystyczna",
    "zaint2": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint3": "wizualizacja danych",
    "zaint1_ile": 50,
    "zaint2_ile": 50,
    "zaint3_ile": 50,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/311_Web_Harvesting/sesja_poranna",
    "pozycja": 8
  },
  {
    "warsztat": "Wróżenie z punktów - ordynacja w eksploracji danych",
    "wiek": 35.737,
    "ile": 7,
    "ile_rezerwa": 0,
    "kobiety": 1,
    "mezczyzni": 5,
    "plec_inne": 1,
    "st_nauk": 100,
    "analizy_0_2": 14.2857,
    "analizy_2_6": 14.2857,
    "analizy_6_wiecej": 28.5714,
    "analizy_R_0_2": 28.5714,
    "analizy_R_2_6": 14.2857,
    "analizy_R_6_wiecej": 14.2857,
    "sesja": "sesja poranna",
    "sciezka": "Klasyfikacja wieloetykietowa z pakietem R",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "analiza tekstu",
    "zaint3": "klastrowanie i segmentacja",
    "zaint1_ile": 57.1429,
    "zaint2_ile": 42.8571,
    "zaint3_ile": 42.8571,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/316_Analiza_Wielowymiarowa/sesja_poranna",
    "pozycja": 9
  }
] ;