/*

dane do zakladki "warsztaty" w wizualizacji
(wygenerowane przy uzyciu R-a)

korzysta z nich funkcja stworzWykresWarsztaty();

opis:

    "warsztat":  nazwa warsztatu
    "wiek": sredni wiek uczestnikow
    "ile": ile osob lacznie zapisanych
    "ile_rezerwa": w tym ile osob to rezerwa
    "kobiety": ilosc kobiet
    "mezczyzni": ilosc mezczyzn
    "plec_inne": ilosc osob, ktora nie okreslila plci
    "st_nauk": procent osob ze stopniem mgr lub dr
    "analizy_0_2": procent osob z doswiadczeniem w analizach od 0 do 2 lat <0,2>
    "analizy_2_6": procent osob z doswiadczeniem w analizach od 2 do 6 lat (2,6)
    "analizy_6_wiecej": procent osob z doswiadczeniem w analizach powyzej 6 lat <6, +inf)
    "analizy_R_0_2": procent osob z doswiadczeniem w R od 0 do 2 lat <0,2>
    "analizy_R_2_6": procent osob z doswiadczeniem w R od 2 do 6 lat (2,6)
    "analizy_R_6_wiecej": procent osob z doswiadczeniem w R powyzej 6 lat <6, +inf)
    "sesja": czas odbywania sie warsztatu: sesja poranna lub popoludniowa
    "sciezka": warsztat z sesji popludniowej, najczesciej wybierany przez uczestnikow tego warsztatu
    "zaint1": pierwsze najczestsze zainteresowanei uczestnikow 
    "zaint2": drugie najczestsze zainteresowanei uczestnikow
    "zaint3": trzecie najczestsze zainteresowanei uczestnikow
    "zaint1_ile": procent osob z zainteresowaniem pierwszym
    "zaint2_ile": procent osob z zainteresowaniem drugim
    "zaint3_ile": procent osob z zainteresowaniem trzecim
    "url": adres internetowy z opisem warsztatu
    "pozycja": nr w rankingu warsztatu wg popularnosci (ew. alfabetu),  oddzielny dla kazdej z sesji

*/

var daneWarsztaty = [
  {
    "warsztat": "Kombajn do uczenia maszynowego - MLR w praktyce",
    "wiek": 32.5333,
    "ile": 29,
    "ile_rezerwa": 9,
    "kobiety": 3,
    "mezczyzni": 24,
    "plec_inne": 2,
    "st_nauk": 55.1724,
    "analizy_0_2": 31.0345,
    "analizy_2_6": 24.1379,
    "analizy_6_wiecej": 27.5862,
    "analizy_R_0_2": 44.8276,
    "analizy_R_2_6": 31.0345,
    "analizy_R_6_wiecej": 6.8966,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "wizualizacja danych",
    "zaint3": "Big Data i hurtownie danych",
    "zaint1_ile": 68.9655,
    "zaint2_ile": 58.6207,
    "zaint3_ile": 44.8276,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/313_Uczenie_Maszynowe_Narzedzia/sesja_popoludniowa",
    "pozycja": 1
  },
  {
    "warsztat": "Text mining w R",
    "wiek": 30.2353,
    "ile": 27,
    "ile_rezerwa": 7,
    "kobiety": 11,
    "mezczyzni": 11,
    "plec_inne": 5,
    "st_nauk": 48.1481,
    "analizy_0_2": 33.3333,
    "analizy_2_6": 18.5185,
    "analizy_6_wiecej": 18.5185,
    "analizy_R_0_2": 51.8519,
    "analizy_R_2_6": 14.8148,
    "analizy_R_6_wiecej": 3.7037,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "analiza tekstu",
    "zaint3": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint1_ile": 55.5556,
    "zaint2_ile": 44.4444,
    "zaint3_ile": 40.7407,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/317_Grafy_Analiza_Tekstu/sesja_popoludniowa",
    "pozycja": 2
  },
  {
    "warsztat": "mirt: skalowanie odpowiedzi lepsze niż PCA",
    "wiek": 31.1359,
    "ile": 19,
    "ile_rezerwa": 0,
    "kobiety": 6,
    "mezczyzni": 11,
    "plec_inne": 2,
    "st_nauk": 36.8421,
    "analizy_0_2": 26.3158,
    "analizy_2_6": 26.3158,
    "analizy_6_wiecej": 21.0526,
    "analizy_R_0_2": 31.5789,
    "analizy_R_2_6": 31.5789,
    "analizy_R_6_wiecej": 10.5263,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "R w biznesie",
    "zaint3": "metodologia statystyczna",
    "zaint1_ile": 63.1579,
    "zaint2_ile": 57.8947,
    "zaint3_ile": 52.6316,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/316_Analiza_Wielowymiarowa/sesja_popoludniowa",
    "pozycja": 3
  },
  {
    "warsztat": "Efektywna i efektowna wizualizacja w ggplot2",
    "wiek": 38.4326,
    "ile": 18,
    "ile_rezerwa": 0,
    "kobiety": 5,
    "mezczyzni": 11,
    "plec_inne": 2,
    "st_nauk": 66.6667,
    "analizy_0_2": 22.2222,
    "analizy_2_6": 11.1111,
    "analizy_6_wiecej": 33.3333,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 0,
    "analizy_R_6_wiecej": 16.6667,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "tworzenie i wizualizacja map",
    "zaint3": "Big Data i hurtownie danych",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 55.5556,
    "zaint3_ile": 50,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/315_Wizualizacje/sesja_popoludniowa",
    "pozycja": 4
  },
  {
    "warsztat": "Klasyfikacja wieloetykietowa z pakietem R",
    "wiek": 32.6114,
    "ile": 16,
    "ile_rezerwa": 0,
    "kobiety": 3,
    "mezczyzni": 12,
    "plec_inne": 1,
    "st_nauk": 56.25,
    "analizy_0_2": 12.5,
    "analizy_2_6": 37.5,
    "analizy_6_wiecej": 37.5,
    "analizy_R_0_2": 43.75,
    "analizy_R_2_6": 25,
    "analizy_R_6_wiecej": 18.75,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "klastrowanie i segmentacja",
    "zaint2": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint3": "R w biznesie",
    "zaint1_ile": 43.75,
    "zaint2_ile": 43.75,
    "zaint3_ile": 37.5,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/314_Uczenie_Maszynowe_Metody/sesja_popoludniowa",
    "pozycja": 5
  },
  {
    "warsztat": "Web scraping w R i nie tylko",
    "wiek": 30.9205,
    "ile": 14,
    "ile_rezerwa": 0,
    "kobiety": 3,
    "mezczyzni": 9,
    "plec_inne": 2,
    "st_nauk": 78.5714,
    "analizy_0_2": 7.1429,
    "analizy_2_6": 35.7143,
    "analizy_6_wiecej": 35.7143,
    "analizy_R_0_2": 21.4286,
    "analizy_R_2_6": 42.8571,
    "analizy_R_6_wiecej": 14.2857,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "R w biznesie",
    "zaint3": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint1_ile": 57.1429,
    "zaint2_ile": 50,
    "zaint3_ile": 42.8571,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/311_Web_Harvesting/sesja_popoludniowa",
    "pozycja": 6
  },
  {
    "warsztat": "Złożone schematy doboru próby - pakiet survey",
    "wiek": 29.0705,
    "ile": 13,
    "ile_rezerwa": 0,
    "kobiety": 5,
    "mezczyzni": 8,
    "plec_inne": 0,
    "st_nauk": 30.7692,
    "analizy_0_2": 30.7692,
    "analizy_2_6": 30.7692,
    "analizy_6_wiecej": 23.0769,
    "analizy_R_0_2": 53.8462,
    "analizy_R_2_6": 30.7692,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "metodologia statystyczna",
    "zaint3": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint1_ile": 61.5385,
    "zaint2_ile": 53.8462,
    "zaint3_ile": 53.8462,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/310_Sondaze/sesja_popoludniowa",
    "pozycja": 7
  },
  {
    "warsztat": "Zastosowanie R w Power BI",
    "wiek": 30.4033,
    "ile": 12,
    "ile_rezerwa": 0,
    "kobiety": 4,
    "mezczyzni": 7,
    "plec_inne": 1,
    "st_nauk": 50,
    "analizy_0_2": 33.3333,
    "analizy_2_6": 16.6667,
    "analizy_6_wiecej": 25,
    "analizy_R_0_2": 58.3333,
    "analizy_R_2_6": 16.6667,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "R w biznesie",
    "zaint2": "Big Data i hurtownie danych",
    "zaint3": "tworzenie raportów i dashboardów",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 58.3333,
    "zaint3_ile": 58.3333,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/312_Uczenie_Maszynowe_Microsoft_Self_BI_Services/sesja_popoludniowa",
    "pozycja": 8
  },
  {
    "warsztat": "Nie pisz kodu, pisz prozę - wprowadzenie do pakietu dplyr",
    "wiek": 34.2215,
    "ile": 10,
    "ile_rezerwa": 0,
    "kobiety": 4,
    "mezczyzni": 4,
    "plec_inne": 2,
    "st_nauk": 60,
    "analizy_0_2": 20,
    "analizy_2_6": 20,
    "analizy_6_wiecej": 40,
    "analizy_R_0_2": 70,
    "analizy_R_2_6": 0,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja popoludniowa",
    "sciezka": "brak",
    "zaint1": "wizualizacja danych",
    "zaint2": "metodologia statystyczna",
    "zaint3": "badania kliniczne",
    "zaint1_ile": 40,
    "zaint2_ile": 30,
    "zaint3_ile": 20,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/318_Wydajnosc/sesja_popoludniowa",
    "pozycja": 9
  },
  {
    "warsztat": "Machine Learning w R przy użyciu H2O",
    "wiek": 31.8228,
    "ile": 28,
    "ile_rezerwa": 8,
    "kobiety": 8,
    "mezczyzni": 19,
    "plec_inne": 1,
    "st_nauk": 39.2857,
    "analizy_0_2": 42.8571,
    "analizy_2_6": 21.4286,
    "analizy_6_wiecej": 14.2857,
    "analizy_R_0_2": 46.4286,
    "analizy_R_2_6": 25,
    "analizy_R_6_wiecej": 7.1429,
    "sesja": "sesja poranna",
    "sciezka": "Kombajn do uczenia maszynowego - MLR w praktyce",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "wizualizacja danych",
    "zaint3": "Big Data i hurtownie danych",
    "zaint1_ile": 67.8571,
    "zaint2_ile": 50,
    "zaint3_ile": 39.2857,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/313_Uczenie_Maszynowe_Narzedzia/sesja_poranna",
    "pozycja": 1
  },
  {
    "warsztat": "Analiza danych sondażowych w R",
    "wiek": 32.1993,
    "ile": 26,
    "ile_rezerwa": 6,
    "kobiety": 7,
    "mezczyzni": 14,
    "plec_inne": 5,
    "st_nauk": 57.6923,
    "analizy_0_2": 11.5385,
    "analizy_2_6": 30.7692,
    "analizy_6_wiecej": 26.9231,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 15.3846,
    "analizy_R_6_wiecej": 3.8462,
    "sesja": "sesja poranna",
    "sciezka": "mirt: skalowanie odpowiedzi lepsze niż PCA",
    "zaint1": "wizualizacja danych",
    "zaint2": "R w badaniach społecznych",
    "zaint3": "analiza tekstu",
    "zaint1_ile": 53.8462,
    "zaint2_ile": 50,
    "zaint3_ile": 46.1538,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/310_Sondaze/sesja_poranna",
    "pozycja": 2
  },
  {
    "warsztat": "Interaktywne wizualizacje w R i plotly - case study",
    "wiek": 33.5271,
    "ile": 24,
    "ile_rezerwa": 4,
    "kobiety": 5,
    "mezczyzni": 15,
    "plec_inne": 4,
    "st_nauk": 66.6667,
    "analizy_0_2": 0,
    "analizy_2_6": 29.1667,
    "analizy_6_wiecej": 50,
    "analizy_R_0_2": 45.8333,
    "analizy_R_2_6": 20.8333,
    "analizy_R_6_wiecej": 12.5,
    "sesja": "sesja poranna",
    "sciezka": "Efektywna i efektowna wizualizacja w ggplot2",
    "zaint1": "wizualizacja danych",
    "zaint2": "metodologia statystyczna",
    "zaint3": "R w biznesie",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 41.6667,
    "zaint3_ile": 41.6667,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/315_Wizualizacje/sesja_poranna",
    "pozycja": 3
  },
  {
    "warsztat": "XGBoost rządzi",
    "wiek": 31.1273,
    "ile": 21,
    "ile_rezerwa": 1,
    "kobiety": 3,
    "mezczyzni": 17,
    "plec_inne": 1,
    "st_nauk": 66.6667,
    "analizy_0_2": 28.5714,
    "analizy_2_6": 19.0476,
    "analizy_6_wiecej": 33.3333,
    "analizy_R_0_2": 28.5714,
    "analizy_R_2_6": 33.3333,
    "analizy_R_6_wiecej": 19.0476,
    "sesja": "sesja poranna",
    "sciezka": "Kombajn do uczenia maszynowego - MLR w praktyce",
    "zaint1": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint2": "metodologia statystyczna",
    "zaint3": "R w biznesie",
    "zaint1_ile": 66.6667,
    "zaint2_ile": 47.619,
    "zaint3_ile": 47.619,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/314_Uczenie_Maszynowe_Metody/sesja_poranna",
    "pozycja": 4
  },
  {
    "warsztat": "Social Network Analysis w R",
    "wiek": 33.8736,
    "ile": 20,
    "ile_rezerwa": 0,
    "kobiety": 5,
    "mezczyzni": 11,
    "plec_inne": 4,
    "st_nauk": 60,
    "analizy_0_2": 25,
    "analizy_2_6": 25,
    "analizy_6_wiecej": 30,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 15,
    "analizy_R_6_wiecej": 15,
    "sesja": "sesja poranna",
    "sciezka": "Text mining w R",
    "zaint1": "R w biznesie",
    "zaint2": "analiza tekstu",
    "zaint3": "R w badaniach społecznych",
    "zaint1_ile": 60,
    "zaint2_ile": 45,
    "zaint3_ile": 45,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/317_Grafy_Analiza_Tekstu/sesja_poranna",
    "pozycja": 5
  },
  {
    "warsztat": "Kiedy brakuje wydajności... R i C++ = Rcpp",
    "wiek": 26.691,
    "ile": 16,
    "ile_rezerwa": 0,
    "kobiety": 6,
    "mezczyzni": 9,
    "plec_inne": 1,
    "st_nauk": 37.5,
    "analizy_0_2": 31.25,
    "analizy_2_6": 37.5,
    "analizy_6_wiecej": 12.5,
    "analizy_R_0_2": 37.5,
    "analizy_R_2_6": 37.5,
    "analizy_R_6_wiecej": 12.5,
    "sesja": "sesja poranna",
    "sciezka": "Text mining w R",
    "zaint1": "wizualizacja danych",
    "zaint2": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint3": "tworzenie raportów i dashboardów",
    "zaint1_ile": 75,
    "zaint2_ile": 56.25,
    "zaint3_ile": 43.75,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/318_Wydajnosc/sesja_poranna",
    "pozycja": 6
  },
  {
    "warsztat": "Wróżenie z punktów - ordynacja w eksploracji danych",
    "wiek": 34.7629,
    "ile": 14,
    "ile_rezerwa": 0,
    "kobiety": 2,
    "mezczyzni": 10,
    "plec_inne": 2,
    "st_nauk": 78.5714,
    "analizy_0_2": 28.5714,
    "analizy_2_6": 14.2857,
    "analizy_6_wiecej": 28.5714,
    "analizy_R_0_2": 50,
    "analizy_R_2_6": 14.2857,
    "analizy_R_6_wiecej": 7.1429,
    "sesja": "sesja poranna",
    "sciezka": "Nie pisz kodu, pisz prozę - wprowadzenie do pakietu dplyr",
    "zaint1": "metodologia statystyczna",
    "zaint2": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint3": "wizualizacja danych",
    "zaint1_ile": 42.8571,
    "zaint2_ile": 42.8571,
    "zaint3_ile": 42.8571,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/316_Analiza_Wielowymiarowa/sesja_poranna",
    "pozycja": 7
  },
  {
    "warsztat": "MicrosoftML - State of the art Machine Learning Microsoft",
    "wiek": 30.6799,
    "ile": 13,
    "ile_rezerwa": 0,
    "kobiety": 6,
    "mezczyzni": 7,
    "plec_inne": 0,
    "st_nauk": 61.5385,
    "analizy_0_2": 30.7692,
    "analizy_2_6": 30.7692,
    "analizy_6_wiecej": 30.7692,
    "analizy_R_0_2": 69.2308,
    "analizy_R_2_6": 23.0769,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja poranna",
    "sciezka": "Zastosowanie R w Power BI",
    "zaint1": "Big Data i hurtownie danych",
    "zaint2": "R w biznesie",
    "zaint3": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint1_ile": 76.9231,
    "zaint2_ile": 76.9231,
    "zaint3_ile": 76.9231,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/312_Uczenie_Maszynowe_Microsoft_Self_BI_Services/sesja_poranna",
    "pozycja": 8
  },
  {
    "warsztat": "Pakiet rvest, czyli web scrapingu wybrane przypadki",
    "wiek": 31.6845,
    "ile": 12,
    "ile_rezerwa": 0,
    "kobiety": 3,
    "mezczyzni": 7,
    "plec_inne": 2,
    "st_nauk": 16.6667,
    "analizy_0_2": 33.3333,
    "analizy_2_6": 0,
    "analizy_6_wiecej": 33.3333,
    "analizy_R_0_2": 33.3333,
    "analizy_R_2_6": 25,
    "analizy_R_6_wiecej": 0,
    "sesja": "sesja poranna",
    "sciezka": "Text mining w R",
    "zaint1": "wizualizacja danych",
    "zaint2": "metodologia statystyczna",
    "zaint3": "statystyczne uczenie maszynowe i modele predykcyjne",
    "zaint1_ile": 58.3333,
    "zaint2_ile": 50,
    "zaint3_ile": 41.6667,
    "url": "https://github.com/whyR-conference/warsztaty/tree/master/311_Web_Harvesting/sesja_poranna",
    "pozycja": 9
  }
]  ;